import type { NextPage } from 'next'
import Head from 'next/head'

import { SkillsGrid } from '../components/SkillsGrid'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Resume</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Jonas Costa Silva</h1>

        <div style={{ height: '3rem' }} />

        <div className={styles.contactGrid}>
          <div className={styles.gridItem}>
            <h3>E-mail</h3>
            <div className={styles.gridItemDivider} />
            <h4>email@jonascsilva.com</h4>
          </div>
          <div className={styles.gridItem}>
            <h3>Telefone</h3>
            <div className={styles.gridItemDivider} />
            <h4>(47) 99952-3329</h4>
          </div>
          <div className={styles.gridItem}>
            <h3>Endereço</h3>
            <div className={styles.gridItemDivider} />
            <h4>Joinville, Santa Catarina, Brasil</h4>
          </div>
        </div>

        <div style={{ height: '3rem' }} />

        <div className={styles.sectionsGrid}>
          <h2>FORMAÇÃO</h2>
          <div />
          <h2>LINKS</h2>
          <div />
          <h2>COMPETÊNCIAS</h2>
          <SkillsGrid
            skills={[
              { name: 'HTML', skillLevel: 3 },
              { name: 'Next.js', skillLevel: 3 },
              { name: 'JavaScript', skillLevel: 3 },
              { name: 'Flutter', skillLevel: 2 },
              { name: 'CSS', skillLevel: 3 },
              { name: 'Unity', skillLevel: 4 },
              { name: 'MySQL', skillLevel: 2 },
              { name: 'Unreal Engine', skillLevel: 2 },
              { name: 'Node.js', skillLevel: 3 },
              { name: 'Tauri', skillLevel: 3 },
              { name: 'React Native', skillLevel: 3 },
              { name: 'TypeScript', skillLevel: 4 },
              { name: 'React', skillLevel: 3 },
              { name: 'Angular', skillLevel: 1 }
            ]}
          />
          <h2>IDIOMAS</h2>
          <SkillsGrid skills={[{ name: 'Inglês', skillLevel: 3 }]} />
        </div>
      </main>
    </div>
  )
}

export default Home
